backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

site_url: https://transcendent-cucurucho-537ce5.netlify.app

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Yayınlanma Tarihi", name: "date", widget: "datetime"}
      - {label: "PDF Dosyası Seç", name: "pdf_file", widget: "file", required: false}
      - {label: "Yazı İçeriği (Opsiyonel)", name: "body", widget: "markdown", required: false}
